### ISSUE TITLE
Przeglądnięcie i wybór fontów

### ISSUE THREAD

**Issue by dikey94** [kmisztal/TLetters#13]
Na gicie jest folder z fontami. Należy wybrać te, które nadają się do użytku - posiadają polskie litery i mają odpowiedni format.

Trzeba stworzyć klasę, która jako argument przyjmuje plik z fontem oraz posiada metodę typu boolean, która zwraca wynik ewaluacji powyższych warunków.

**Comment by polarny** [comment]
To oznacza, że mamy stworzyć klasę, która automatycznie ewaluuje fonty na podstawie pliku? Czy może raczej sami wyewaluować dostarczone fonty, a klasa będzie tylko sprawdzać czy podany font jest wśród tych które zdecydowaliśmy się supportować?
