### ISSUE TITLE
ImageGenerator //2 osoby

### ISSUE THREAD

**Issue by dikey94** [kmisztal/TLetters#8]
Napisz klasę ImageGenerator, która będzie generowała obrazek w formacie jpg lub png, według wcześniej podanych parametrów. Klasa będzie zawierała metodę getGeneratedImage, zwracającą BufferedImage. Wygenerowany obrazek będzie zawierał tekst podany przez użytkownika. Ważne jest, by obrazek nie zawierał dodatkowych “pustych” przestrzeni, to znaczy litery powinny stykać się z krawędziami. Użytkownik może ustawić takie parametry jak:

- krój czcionki 
- rozmiar czcionki
- tekst
- ziarno

**Comment by kmisztal** [comment]
zadanie jest podobne do #9 
czy tak ma być?

**Comment by dikey94** [comment]
Ja to rozumiem tak, że ImageGenerator dostarcza nam obrazki, z których możemy wycinać litery. Z kolei GlyphExtracter wycina z obrazków pojedyncze litery.

 

Damian Kulig
Phone: +48 607 236 682
E-mail:  <mailto:mail@damiankulig.com> mail@damiankulig.com
WWW:  <http://www.damiankulig.com/> www.damiankulig.com

**Comment by kmisztal** [comment]
ok
